from __future__ import annotations

from enum import Enum


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IntentLabel(str, Enum):
    SHORTAGE = "SHORTAGE"
    RECALL = "RECALL"
    SUBSTITUTION = "SUBSTITUTION"
    PRIOR_AUTHORIZATION = "PRIOR_AUTHORIZATION"
    DENIAL_APPEAL = "DENIAL_APPEAL"
    FORMULARY_ACCESS = "FORMULARY_ACCESS"
    AUTHENTICITY = "AUTHENTICITY"
    COMPOUNDING_COMPLIANCE = "COMPOUNDING_COMPLIANCE"
    PATIENT_COUNSELING = "PATIENT_COUNSELING"
    MULTI_AGENT_CASE = "MULTI_AGENT_CASE"
    GENERAL = "GENERAL"
